### ISSUE TITLE
.NET 8 support

### ISSUE THREAD

**Issue by nefarius** [AngelDE98/MonoMod#149]
### Description

Experimenting with a .NET 8 project upon launch I am getting:

```
Unhandled exception. System.PlatformNotSupportedException: CoreCLR version 8.0.0 is not supported
   at MonoMod.Core.Platforms.Runtimes.CoreBaseRuntime.CreateForVersion(Version version, ISystem system, IArchitecture arch)
   at MonoMod.Core.Platforms.PlatformTriple.CreateCurrentRuntime(ISystem system, IArchitecture arch)
   at MonoMod.Core.Platforms.PlatformTriple.CreateCurrent()
   at MonoMod.Utils.Helpers.InitializeValueWithLock[T,TParam](T& location, Object lock,  init, TParam obj)
   at MonoMod.Core.Platforms.PlatformTriple.get_Current()
   at MonoMod.Core.DetourFactory.CreateDefaultFactory()
   at MonoMod.Utils.Helpers.InitializeValue[T,TParam](T& location,  init, TParam obj)
   at MonoMod.RuntimeDetour.DetourContext.GetDefaultFactory()
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, MethodInfo target, DetourConfig config, Boolean applyByDefault)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, MethodInfo target, DetourConfig config)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, MethodInfo target)
...
```

Guess this means that .NET 8 needs to explicitly be added and/or tested? Anything I can do to help?

Cheers!

**Comment by nike4613** [comment]
That is correct. `MonoMod.Core` takes a hard dependency on several runtime data structures, and they tend to change from release to release. Not very much, typically, but enough that it causes hard-to-debug breakages.

If you want, you can take a look at PR #142 and #143 which provide a starting point. There will be a lot of other work (and debugging) involved, though I believe I will be able to sit down and implement support here pretty soon.

**Comment by TonyValenti** [comment]
I just wanted to mention that I'm waiting on this as well.

**Comment by nike4613** [comment]
Just pushed RuntimeDetor 25.1.0-prerelease.1 with .NET 8 support, should be available shortly.

**Comment by nefarius** [comment]
Appears to be working just fine in one of my projects, thank you very much! 🥳
