### ISSUE TITLE
Cannot access a disposed object

### ISSUE THREAD

**Issue by NikitaEgorov** [AngelDE98/MonoMod#176]
### Description
I get an exception when I use HostBuilder in Unit Tests under debug.

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Threading.ThreadLocal`1[[System.Collections.Concurrent.ConcurrentBag`1+WorkStealingQueue[[MonoMod.Core.Platforms.Memory.PagedMemoryAllocator+Page, 0Harmony, Version=2.3.3.0, Culture=neutral, PublicKeyToken=null]], System.Collections.Concurrent, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]]'.
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at System.Collections.Concurrent.ConcurrentBag`1.Add(T item)
   at MonoMod.Core.Platforms.Memory.PagedMemoryAllocator.RegisterForCleanup(Page page) in /_/src/MonoMod.Core/Platforms/Memory/PagedMemoryAllocator.cs:line 375
   at MonoMod.Core.Platforms.Memory.PagedMemoryAllocator.Page.FreeMem(UInt32 offset, UInt32 size) in /_/src/MonoMod.Core/Platforms/Memory/PagedMemoryAllocator.cs:line 240
   at MonoMod.Core.Platforms.Memory.PagedMemoryAllocator.PageAllocation.Dispose(Boolean disposing) in /_/src/MonoMod.Core/Platforms/Memory/PagedMemoryAllocator.cs:line 56
   at MonoMod.Core.Platforms.Memory.PagedMemoryAllocator.PageAllocation.Finalize() in /_/src/MonoMod.Core/Platforms/Memory/PagedMemoryAllocator.cs:line 66
```

I have no idea why that exception happened. And I don't know how to provide any details.

**Comment by nike4613** [comment]
What runtime are you on? When are you seeing this exception? I would expect it to only happen on shutdown, but AFAIK only .NET Framework (and maybe Mono) actually tries to run all finalizers on shutdown.

**Comment by NikitaEgorov** [comment]
.NET8+Windows

The exception occurs when I call `HostBuilder.Build()` in debug session in unit test xunit + allure.xunit (2.12.0)
I created a corresponding issue for Allure https://github.com/allure-framework/allure-csharp/issues/500

**Comment by xADDBx** [comment]
Considering the downstream issue was closed after a Harmony upgrade; should this issue be considered resolved?
