### ISSUE TITLE
Unable to Load Temporary Native Library due to executable stack Restriction

### ISSUE THREAD

**Issue by robert94p** [AngelDE98/MonoMod#198]
When using MonoMod.Core via HarmonyLib, an error occurs during the dynamic generation and loading of the native library (/tmp/mm-exhelper.so.XXXXXX) under systems with stricter security policies. The issue arises because the temporary native library requires an executable stack, which is prohibited in certain environments. This results in the following exception:
`System.DllNotFoundException: Unable to load shared library '/tmp/mm-exhelper.so.wGm60g' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /tmp/mm-exhelper.so.wGm60g: cannot enable executable stack as shared object requires: Permission denied`

This happens because the dynamically created library requires an executable stack, which is restricted by the host system's security settings. This issue is particularly problematic in environments where:
- Policies such as noexec or SELinux/AppArmor block such operations.
- Executable stacks are explicitly disabled by the operating system.

**Comment by nike4613** [comment]
I remember seeing this before, I don't remember what the solution is. The exception helper does not use executable stacks or anything else particularly strange.

**Comment by robert94p** [comment]
One possible solution could be disabling executable stack enforcement on the host operating system, but I would prefer not to do this, as I am neither responsible for it nor have access. My application is running in a Docker container on this host

**Comment by robert94p** [comment]
Is the library /tmp/mm-exhelper.so.wGm60g built without the -z noexecstack flag? The output of readelf does not show the presence of a .GNU-stack section, which suggests that an executable stack might be enabled by default.

**Comment by nike4613** [comment]
That library is built from assembly. It uses default linker flags. Why would executable stack be a presumed on-by-default option?

**Comment by robert94p** [comment]
I don’t have much experience working with libraries like this. However, I made an assumption based on the information found [here](https://wiki.gentoo.org/wiki/Hardened/GNU_stack_quickstart#Finding_ELFs_that_ask_for_an_executable_stack), which states:
> If an assembler source contains no GNU-stack note, the system by default assumes that an executable stack may be required.

**Comment by robert94p** [comment]
@nike4613, would it be possible to build the library with the executable stack requirement disabled?

**Comment by sjtuross** [comment]
On a Synology system using Harmony, I encountered a similar issue:

```
2024-09-12 23:56:04.908 Debug: /tmp/mm-exhelper.so.WV5XqM.so: cannot open shared object file: No such file or directory
2024-09-12 23:56:04.908 Debug:    at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at HarmonyLib.PatchProcessor.Patch()
   at HarmonyLib.Harmony.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler, HarmonyMethod finalizer)
```

The problem occurs because files in the /tmp directory do not have executable permissions, leading to this error. A workaround is to run `mount -o remount,exec /tmp` after every system restart.

Is there a way to configure the path used for exhelper so it doesn’t rely on /tmp?

**Comment by nike4613** [comment]
> Is there a way to configure the path used for exhelper so it doesn’t rely on /tmp?

Where else would we drop the library? It's currently [hardcoded using a `mkstemp` format string](https://github.com/MonoMod/MonoMod/blob/reorganize/src/MonoMod.Core/Platforms/Systems/LinuxSystem.cs#L372).

**Comment by sjtuross** [comment]
How about using an environment variable to allow the user or developer to specify?

**Comment by robert94p** [comment]
Will there be no changes to this issue? Or is there a way to work around it?

**Comment by nike4613** [comment]
I haven't had an opportunity to touch it. PRs are always welcome. Should be just adding a section to the assembly files and re-assembling/linking.
