### ISSUE TITLE
IL Compile Error with Runtime Detour 25.2.0 and 25.2.1

### ISSUE THREAD

**Issue by ds5678** [AngelDE98/MonoMod#199]
### Description

I was updating HarmonyX for your recent .NET 9 support and discovered a potential bug. One unit test fails to pass. This bug was introduced in the 25.2.0 release and persists in the 25.2.1 release.

### Example

https://github.com/BepInEx/HarmonyX/blob/ef84f6e44494d1c5097c2049b0efc9e02f917665/HarmonyTests/Tools/TestGettingInstructions.cs#L40

```
 Test_GetCurrentInstructions
   Source: TestGettingInstructions.cs line 40
   Duration: 11 ms

  Message: 
HarmonyLib.HarmonyException : IL Compile Error (unknown location)
  ----> HarmonyLib.HarmonyException : IL Compile Error (unknown location)
  ----> HarmonyLib.HarmonyException : IL Compile Error (unknown location)
  ----> System.Collections.Generic.KeyNotFoundException : The given key 'V_4' was not present in the dictionary.

  Stack Trace: 
PatchClassProcessor.ReportException(Exception exception, MethodBase original) line 346
PatchClassProcessor.Patch() line 118
Test_GettingInstructions.Test_GetCurrentInstructions() line 54
RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
--HarmonyException
ManagedMethodPatcher.DetourTo(MethodBase replacement) line 43
PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo) line 57
--HarmonyException
HarmonyManipulator.WriteImpl() line 448
HarmonyManipulator.Process(ILContext ilContext, MethodBase originalMethod) line 144
HarmonyManipulator.Manipulate(MethodBase original, PatchInfo patchInfo, ILContext ctx) line 89
HarmonyManipulator.Manipulate(MethodBase original, ILContext ctx) line 99
ManagedMethodPatcher.Manipulator(ILContext ctx) line 57
ILContext.Invoke(Manipulator manip)
ManagedDetourState.InvokeManipulator(ILHookEntry entry, MethodDefinition def)
ManagedDetourState.UpdateEndOfChain()
ManagedDetourState.AddILHook(SingleILHookState ilhook, Boolean takeLock)
ILHook.Apply()
ManagedMethodPatcher.DetourTo(MethodBase replacement) line 39
--KeyNotFoundException
Dictionary`2.get_Item(TKey key)
ILManipulator.Prepare(Func`2 getLocal, Func`1 defineLabel) line 278
ILManipulator.ApplyTranspilers(ILGenerator il, MethodBase original, Func`2 getLocal, Func`1 defineLabel) line 224
ILManipulator.WriteTo(MethodBody body, MethodBase original) line 340
HarmonyManipulator.WriteTranspilers() line 339
HarmonyManipulator.WriteImpl() line 382

  Standard Output: 
### HarmonyLibTests.Tools.Test_GettingInstructions.Test_GetCurrentInstructions
[Info]
	### Harmony id=instructions, version=2.13.0.0, location=E:\repos\HarmonyX\HarmonyTests\bin\Debug\net8.0\0Harmony.dll, env/clr=8.0.11, platform=Win32NT, ptrsize:runtime=8
	### Started from void HarmonyLibTests.Tools.Test_GettingInstructions::Test_GetCurrentInstructions(), location E:\repos\HarmonyX\HarmonyTests\bin\Debug\net8.0\HarmonyTests.dll
	### At 2024-11-22 11.04.59
[Info]
	Patching int HarmonyLibTests.Tools.InstructionTest::Method(string input) with 0 prefixes, 0 postfixes, 1 transpilers, 0 finalizers
	1 transpilers:
	* static System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> HarmonyLibTests.Tools.InstructionTest+Patch::Transpiler(System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> instructions)
	
[Info]
	Running ILHook manipulator on int HarmonyLibTests.Tools.InstructionTest::Method(string input)
[Info]
	Transpiling int HarmonyLibTests.Tools.InstructionTest::Method(string input)
[Error]
	Failed to patch int HarmonyLibTests.Tools.InstructionTest::Method(string input): System.Collections.Generic.KeyNotFoundException: The given key 'V_4' was not present in the dictionary.
	   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
	   at HarmonyLib.Internal.Patching.ILManipulator.Prepare(Func`2 getLocal, Func`1 defineLabel) in E:\repos\HarmonyX\Harmony\Internal\Patching\ILManipulator.cs:line 278
	   at HarmonyLib.Internal.Patching.ILManipulator.ApplyTranspilers(ILGenerator il, MethodBase original, Func`2 getLocal, Func`1 defineLabel) in E:\repos\HarmonyX\Harmony\Internal\Patching\ILManipulator.cs:line 224
	   at HarmonyLib.Internal.Patching.ILManipulator.WriteTo(MethodBody body, MethodBase original) in E:\repos\HarmonyX\Harmony\Internal\Patching\ILManipulator.cs:line 340
	   at HarmonyLib.Public.Patching.HarmonyManipulator.WriteTranspilers() in E:\repos\HarmonyX\Harmony\Public\Patching\HarmonyManipulator.cs:line 339
	   at HarmonyLib.Public.Patching.HarmonyManipulator.WriteImpl() in E:\repos\HarmonyX\Harmony\Public\Patching\HarmonyManipulator.cs:line 382
[Debug]
	### Exception from user "instructions", Harmony v2.13.0.0
	### Original: int HarmonyLibTests.Tools.InstructionTest::Method(string input)
	### Patch class: HarmonyLibTests.Tools.InstructionTest+Patch
	### HarmonyLib.HarmonyException: IL Compile Error (unknown location)
	###  ---> HarmonyLib.HarmonyException: IL Compile Error (unknown location)
	###  ---> System.Collections.Generic.KeyNotFoundException: The given key 'V_4' was not present in the dictionary.
	###    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
	###    at HarmonyLib.Internal.Patching.ILManipulator.Prepare(Func`2 getLocal, Func`1 defineLabel) in E:\repos\HarmonyX\Harmony\Internal\Patching\ILManipulator.cs:line 278
	###    at HarmonyLib.Internal.Patching.ILManipulator.ApplyTranspilers(ILGenerator il, MethodBase original, Func`2 getLocal, Func`1 defineLabel) in E:\repos\HarmonyX\Harmony\Internal\Patching\ILManipulator.cs:line 224
	###    at HarmonyLib.Internal.Patching.ILManipulator.WriteTo(MethodBody body, MethodBase original) in E:\repos\HarmonyX\Harmony\Internal\Patching\ILManipulator.cs:line 340
	###    at HarmonyLib.Public.Patching.HarmonyManipulator.WriteTranspilers() in E:\repos\HarmonyX\Harmony\Public\Patching\HarmonyManipulator.cs:line 339
	###    at HarmonyLib.Public.Patching.HarmonyManipulator.WriteImpl() in E:\repos\HarmonyX\Harmony\Public\Patching\HarmonyManipulator.cs:line 382
	###    --- End of inner exception stack trace ---
	###    at HarmonyLib.Public.Patching.HarmonyManipulator.WriteImpl() in E:\repos\HarmonyX\Harmony\Public\Patching\HarmonyManipulator.cs:line 448
	###    at HarmonyLib.Public.Patching.HarmonyManipulator.Process(ILContext ilContext, MethodBase originalMethod) in E:\repos\HarmonyX\Harmony\Public\Patching\HarmonyManipulator.cs:line 144
	###    at HarmonyLib.Public.Patching.HarmonyManipulator.Manipulate(MethodBase original, PatchInfo patchInfo, ILContext ctx) in E:\repos\HarmonyX\Harmony\Public\Patching\HarmonyManipulator.cs:line 89
	###    at HarmonyLib.Public.Patching.HarmonyManipulator.Manipulate(MethodBase original, ILContext ctx) in E:\repos\HarmonyX\Harmony\Public\Patching\HarmonyManipulator.cs:line 99
	###    at HarmonyLib.Public.Patching.ManagedMethodPatcher.Manipulator(ILContext ctx) in E:\repos\HarmonyX\Harmony\Public\Patching\ManagedMethodPatcher.cs:line 57
	###    at MonoMod.Cil.ILContext.Invoke(Manipulator manip)
	###    at MonoMod.RuntimeDetour.DetourManager.ManagedDetourState.InvokeManipulator(ILHookEntry entry, MethodDefinition def)
	###    at MonoMod.RuntimeDetour.DetourManager.ManagedDetourState.UpdateEndOfChain()
	###    at MonoMod.RuntimeDetour.DetourManager.ManagedDetourState.AddILHook(SingleILHookState ilhook, Boolean takeLock)
	###    at MonoMod.RuntimeDetour.ILHook.Apply()
	###    at HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo(MethodBase replacement) in E:\repos\HarmonyX\Harmony\Public\Patching\ManagedMethodPatcher.cs:line 39
	###    --- End of inner exception stack trace ---
	###    at HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo(MethodBase replacement) in E:\repos\HarmonyX\Harmony\Public\Patching\ManagedMethodPatcher.cs:line 43
	###    at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo) in E:\repos\HarmonyX\Harmony\Internal\PatchFunctions.cs:line 57
	
[Debug]
	### Exception from user "instructions", Harmony v2.13.0.0
	### Original: int HarmonyLibTests.Tools.InstructionTest::Method(string input)
	### Patch class: HarmonyLibTests.Tools.InstructionTest+Patch
	### HarmonyLib.HarmonyException: IL Compile Error (unknown location)
	###  ---> HarmonyLib.HarmonyException: IL Compile Error (unknown location)
	###  ---> System.Collections.Generic.KeyNotFoundException: The given key 'V_4' was not present in the dictionary.
	###    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
	###    at HarmonyLib.Internal.Patching.ILManipulator.Prepare(Func`2 getLocal, Func`1 defineLabel) in E:\repos\HarmonyX\Harmony\Internal\Patching\ILManipulator.cs:line 278
	###    at HarmonyLib.Internal.Patching.ILManipulator.ApplyTranspilers(ILGenerator il, MethodBase original, Func`2 getLocal, Func`1 defineLabel) in E:\repos\HarmonyX\Harmony\Internal\Patching\ILManipulator.cs:line 224
	###    at HarmonyLib.Internal.Patching.ILManipulator.WriteTo(MethodBody body, MethodBase original) in E:\repos\HarmonyX\Harmony\Internal\Patching\ILManipulator.cs:line 340
	###    at HarmonyLib.Public.Patching.HarmonyManipulator.WriteTranspilers() in E:\repos\HarmonyX\Harmony\Public\Patching\HarmonyManipulator.cs:line 339
	###    at HarmonyLib.Public.Patching.HarmonyManipulator.WriteImpl() in E:\repos\HarmonyX\Harmony\Public\Patching\HarmonyManipulator.cs:line 382
	###    --- End of inner exception stack trace ---
	###    at HarmonyLib.Public.Patching.HarmonyManipulator.WriteImpl() in E:\repos\HarmonyX\Harmony\Public\Patching\HarmonyManipulator.cs:line 448
	###    at HarmonyLib.Public.Patching.HarmonyManipulator.Process(ILContext ilContext, MethodBase originalMethod) in E:\repos\HarmonyX\Harmony\Public\Patching\HarmonyManipulator.cs:line 144
	###    at HarmonyLib.Public.Patching.HarmonyManipulator.Manipulate(MethodBase original, PatchInfo patchInfo, ILContext ctx) in E:\repos\HarmonyX\Harmony\Public\Patching\HarmonyManipulator.cs:line 89
	###    at HarmonyLib.Public.Patching.HarmonyManipulator.Manipulate(MethodBase original, ILContext ctx) in E:\repos\HarmonyX\Harmony\Public\Patching\HarmonyManipulator.cs:line 99
	###    at HarmonyLib.Public.Patching.ManagedMethodPatcher.Manipulator(ILContext ctx) in E:\repos\HarmonyX\Harmony\Public\Patching\ManagedMethodPatcher.cs:line 57
	###    at MonoMod.Cil.ILContext.Invoke(Manipulator manip)
	###    at MonoMod.RuntimeDetour.DetourManager.ManagedDetourState.InvokeManipulator(ILHookEntry entry, MethodDefinition def)
	###    at MonoMod.RuntimeDetour.DetourManager.ManagedDetourState.UpdateEndOfChain()
	###    at MonoMod.RuntimeDetour.DetourManager.ManagedDetourState.AddILHook(SingleILHookState ilhook, Boolean takeLock)
	###    at MonoMod.RuntimeDetour.ILHook.Apply()
	###    at HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo(MethodBase replacement) in E:\repos\HarmonyX\Harmony\Public\Patching\ManagedMethodPatcher.cs:line 39
	###    --- End of inner exception stack trace ---
	###    at HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo(MethodBase replacement) in E:\repos\HarmonyX\Harmony\Public\Patching\ManagedMethodPatcher.cs:line 43
	###    at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo) in E:\repos\HarmonyX\Harmony\Internal\PatchFunctions.cs:line 57
	
--- HarmonyLibTests.Tools.Test_GettingInstructions.Test_GetCurrentInstructions => Failed:Error
```

**Comment by nike4613** [comment]
AFAIR nothing was touched going in to Core 25.2 in that part of Utils, which if true would mean this is a latent bug somewhere. I can check later today.

**Comment by nike4613** [comment]
Finally getting back to this. Most likely commit to be causing this issue is https://github.com/MonoMod/MonoMod/commit/6b8dc347e5aba728a852bca04c0c9e2ac6f5b46c, though I can't see why it would do so. No changes have been made which affect how locals are named, nor whether the instances are modified.

**Comment by ds5678** [comment]
I have some idea of why this is happening.

If I change this line:

https://github.com/BepInEx/HarmonyX/blob/ef84f6e44494d1c5097c2049b0efc9e02f917665/Harmony/Internal/Patching/ILManipulator.cs#L278

To:
```cs
unresolvedInstruction.Instruction.operand = localsCache.First(pair => pair.Key.Index == varDef.Index).Value;
```
The test passes.

*Copied from Discord*
